import type { PatternConfig } from './types'

export const sama: PatternConfig = {
  id: 'sama',
  name: 'Sama',
  nameSanskrit: 'Sama',
  nameDevanagari: 'साम',
  description: 'Steady forward gaze. Unblinking fixation for concentration and calm.',
  category: 'drishti',
  binduColor: 'lotus',
  trajectory: 'fixation',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0, easing: 'linear' },
  cycleDuration: null,
  defaultSessionDuration: 180_000,
  phases: [
    { type: 'fixation', duration: 60_000, instruction: 'Смотрите на точку, не моргая. Дышите ровно.' },
    { type: 'fixation', duration: 60_000, instruction: 'Продолжайте удерживать взгляд. Отмечайте мысли, не следуя за ними.' },
    { type: 'eyes-closed', duration: 30_000, instruction: 'Закройте глаза. Наблюдайте за ощущениями.' },
    { type: 'fixation', duration: 30_000, instruction: 'Откройте глаза. Мягко верните взгляд к точке.' },
  ],
  audioConfig: { mode: 'drone', frequency: 196, waveform: 'sine', droneIntervals: [1, 1.5, 2.5], singingBowlInterval: 35_000 },
  requiresHeadphones: false,
  instruction: 'Сядьте удобно. Смотрите на светящуюся точку в центре экрана, не отводя взгляда и стараясь не моргать. Голову держите неподвижно. Дышите медленно и ровно. Когда внимание уходит — мягко возвращайте его к точке.',
  effect: 'Успокоение потока мыслей, повышение концентрации, ощущение центрированности. После сессии возможно кратковременное ощущение расширенного восприятия.',
  origins: 'В Натья Шастре Sama описана как взгляд, используемый в начале танца и для изображения божеств. Это базовая практика фиксации взгляда, близкая к Тратаке из йогических текстов.',
  benefits: ['concentration', 'calm', 'mental clarity', 'grounding'],
  defaultBackground: 'fibonacci',
  defaultBackgroundRotation: 'cw',
}

export const alokita: PatternConfig = {
  id: 'alokita',
  name: 'Alokita',
  nameSanskrit: 'Alokita',
  nameDevanagari: 'आलोकित',
  description: 'Wide circular gaze. Activates peripheral vision and vestibular system.',
  category: 'drishti',
  binduColor: 'teal',
  trajectory: 'circular',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0.42, easing: 'sine' },
  cycleDuration: 4000,
  defaultSessionDuration: 180_000,
  phases: [
    { type: 'movement', duration: 60_000, instruction: 'Следите за точкой глазами по кругу. Голова неподвижна.' },
    { type: 'fixation', duration: 15_000, instruction: 'Точка остановилась. Удерживайте взгляд в центре.' },
    { type: 'movement', duration: 60_000, instruction: 'Продолжайте следить. Обратите внимание на периферийное зрение.' },
    { type: 'fixation', duration: 15_000, instruction: 'Пауза. Отметьте, что вы чувствуете.' },
    { type: 'movement', duration: 30_000 },
  ],
  audioConfig: { mode: 'rhythmic', frequency: 396, waveform: 'sine', rhythmBPM: 60 },
  requiresHeadphones: false,
  instruction: 'Следите глазами за точкой, которая движется по кругу. Голову держите неподвижно — работают только глаза. Старайтесь, чтобы движение было плавным, без рывков. Замечайте, что происходит с периферийным зрением.',
  effect: 'Расширение поля восприятия, снижение тоннельного зрения (характерного для тревоги). Мягкая активация вестибулярной системы. Ощущение \'раскрытия\' пространства вокруг.',
  origins: 'Alokita описана в Натья Шастре как широкий, обводящий взгляд. В танце используется для выражения удивления и осматривания пространства. Круговые движения глаз задействуют все шесть глазных мышц.',
  benefits: ['peripheral vision', 'spatial awareness', 'anxiety reduction', 'vestibular activation'],
  defaultBackground: 'seed-of-life',
  defaultBackgroundRotation: 'cw',
}

export const sachi: PatternConfig = {
  id: 'sachi',
  name: 'Sachi',
  nameSanskrit: 'Sachi',
  nameDevanagari: 'साची',
  description: 'Gentle side glance. Short-amplitude bilateral stimulation for beginners.',
  category: 'drishti',
  binduColor: 'saffron',
  trajectory: 'horizontal',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0.3, easing: 'ease-in-out' },
  cycleDuration: 2000,
  defaultSessionDuration: 180_000,
  phases: [
    { type: 'movement', duration: 45_000, instruction: 'Следите за точкой. Амплитуда небольшая — мягкие движения.' },
    { type: 'fixation', duration: 10_000, instruction: 'Пауза. Что вы замечаете?' },
    { type: 'movement', duration: 45_000 },
    { type: 'fixation', duration: 10_000, instruction: 'Отдохните.' },
    { type: 'movement', duration: 45_000 },
    { type: 'fixation', duration: 15_000, instruction: 'Последняя пауза. Отметьте изменения.' },
  ],
  audioConfig: { mode: 'bilateral', frequency: 396, waveform: 'sine' },
  requiresHeadphones: true,
  instruction: 'Точка движется из стороны в сторону с небольшой амплитудой. Следите за ней глазами, не поворачивая головы. Это мягкий вариант билатеральной стимуляции — хорошо подходит для начала.',
  effect: 'Мягкое снижение тревожности. Менее интенсивно, чем полная билатеральная стимуляция. Подходит для первого знакомства с практикой или для дней, когда полная амплитуда ощущается избыточной.',
  origins: 'Sachi — боковой взгляд в индийском танце, один из самых выразительных. Используется для передачи тонких эмоций. В контексте EMDR — укороченные саккады, более щадящий режим стимуляции.',
  benefits: ['gentle anxiety reduction', 'beginner-friendly', 'emotional processing'],
  defaultBackground: 'flower-of-life',
  defaultBackgroundRotation: 'cw',
}

export const pralokita: PatternConfig = {
  id: 'pralokita',
  name: 'Pralokita',
  nameSanskrit: 'Pralokita',
  nameDevanagari: 'प्रलोकित',
  description: 'Side to side eye movement. Core bilateral stimulation, identical to EMDR.',
  category: 'drishti',
  binduColor: 'saffron',
  trajectory: 'horizontal',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0.45, easing: 'ease-in-out' },
  cycleDuration: 1600,
  defaultSessionDuration: 180_000,
  phases: [
    { type: 'movement', duration: 30_000, instruction: 'Следите за точкой глазами. Голова неподвижна.' },
    { type: 'fixation', duration: 10_000, instruction: 'Пауза. Сделайте глубокий вдох.' },
    { type: 'movement', duration: 30_000 },
    { type: 'fixation', duration: 10_000, instruction: 'Что приходит сейчас? Просто отмечайте.' },
    { type: 'movement', duration: 30_000 },
    { type: 'fixation', duration: 10_000 },
    { type: 'movement', duration: 30_000 },
    { type: 'fixation', duration: 10_000, instruction: 'Последний отдых. Дышите.' },
  ],
  audioConfig: { mode: 'bilateral', frequency: 285, waveform: 'sine', bilateralDetune: 2 },
  requiresHeadphones: true,
  instruction: 'Это основной режим билатеральной стимуляции. Точка двигается из стороны в сторону — следите за ней глазами, не поворачивая головы. В паузах — просто отмечайте, какие мысли, образы или ощущения приходят. Не анализируйте, просто наблюдайте.',
  effect: 'Снижение интенсивности тревожных мыслей и эмоциональной нагрузки воспоминаний. Ощущение \'разрядки\'. Мета-анализ 20 исследований подтверждает немедленное снижение яркости тревожных образов и негативных эмоций.',
  origins: 'Pralokita — боковые движения глаз из Натья Шастры. Идентичны билатеральной стимуляции в EMDR (Шапиро, 1989). Три независимых открытия одного механизма: индийский танец, нейронаука REM-сна, клиническая психотерапия.',
  benefits: ['anxiety reduction', 'trauma processing', 'emotional regulation', 'memory reconsolidation'],
  defaultBackground: 'mandala',
  defaultBackgroundRotation: 'cw',
}

export const nimilita: PatternConfig = {
  id: 'nimilita',
  name: 'Nimilita',
  nameSanskrit: 'Nimilita',
  nameDevanagari: 'निमीलित',
  description: 'Half-closed eyes fixation. Deep relaxation and parasympathetic activation.',
  category: 'drishti',
  binduColor: 'indigo',
  trajectory: 'fixation',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0, easing: 'linear' },
  cycleDuration: null,
  defaultSessionDuration: 120_000,
  phases: [
    { type: 'fixation', duration: 30_000, instruction: 'Смотрите на точку. Начинайте мягко прикрывать веки — глаза полуоткрыты.' },
    { type: 'fixation', duration: 30_000, instruction: 'Продолжайте. Направьте внимание внутрь, к ощущениям в теле.' },
    { type: 'eyes-closed', duration: 30_000, instruction: 'Закройте глаза полностью. Дышите животом.' },
    { type: 'fixation', duration: 30_000, instruction: 'Мягко откройте глаза. Верните внимание к точке.' },
  ],
  audioConfig: { mode: 'drone', frequency: 130.81, waveform: 'sine', droneIntervals: [1, 1.5, 2, 0.5], pinkNoise: 0.03 },
  requiresHeadphones: false,
  instruction: 'Мягко прикройте веки — не полностью, а наполовину. Направьте расфокусированный взгляд на тускло светящуюся точку. Не старайтесь видеть чётко. Дышите медленно. Позвольте вниманию направиться внутрь.',
  effect: 'Глубокое расслабление, активация парасимпатической нервной системы. Помогает после интенсивной работы (например, после Pralokita). Снижает частоту сердцебиения, расслабляет мышцы лица и челюсти.',
  origins: 'Nimilita означает \'полузакрытые глаза\'. В Натья Шастре — взгляд, направленный к сердцу. Используется для изображения медитации, молитвы, божественного покоя. Нейрофизиологически — снижение визуальной стимуляции активирует парасимпатику.',
  benefits: ['deep relaxation', 'parasympathetic activation', 'cooldown after processing', 'inner focus'],
  defaultBackground: 'fibonacci',
  defaultBackgroundRotation: 'ccw',
}

export const ullokita: PatternConfig = {
  id: 'ullokita',
  name: 'Ullokita',
  nameSanskrit: 'Ullokita',
  nameDevanagari: 'उल्लोकित',
  description: 'Upward gaze. Vertical movement with upper bias for visualization.',
  category: 'drishti',
  binduColor: 'teal',
  trajectory: 'vertical',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0.42, easing: 'sine', bias: 'up' },
  cycleDuration: 2500,
  defaultSessionDuration: 120_000,
  phases: [
    { type: 'movement', duration: 40_000, instruction: 'Следите за точкой вверх-вниз. Движение мягкое, плавное.' },
    { type: 'fixation', duration: 10_000, instruction: 'Пауза. Точка остановилась наверху.' },
    { type: 'movement', duration: 40_000 },
    { type: 'fixation', duration: 10_000, instruction: 'Отмечайте образы, которые приходят.' },
    { type: 'movement', duration: 20_000 },
  ],
  audioConfig: { mode: 'rhythmic', frequency: 432, waveform: 'triangle', rhythmBPM: 50, pitchBendRange: 15 },
  requiresHeadphones: false,
  instruction: 'Точка движется вверх и вниз, с акцентом на верхнюю часть. Следите глазами. Этот паттерн связан с визуализацией и воображением. Позвольте образам свободно приходить.',
  effect: 'Активация визуальной памяти и воображения. Некоторые отмечают спонтанное появление образов и воспоминаний. Мягкая стимуляция, хорошо работает в сочетании с намерением вспомнить что-то позитивное.',
  origins: 'Ullokita — взгляд вверх в Натья Шастре. Используется для изображения небесных существ, молитвы, воспоминаний. Вертикальные движения глаз задействуют верхнюю и нижнюю прямые мышцы глаза.',
  benefits: ['visualization', 'memory access', 'imagination', 'positive resource building'],
  defaultBackground: 'ripples',
  defaultBackgroundRotation: 'cw',
}

export const anuvritta: PatternConfig = {
  id: 'anuvritta',
  name: 'Anuvritta',
  nameSanskrit: 'Anuvritta',
  nameDevanagari: 'अनुवृत्त',
  description: 'Rapid vertical saccades. REM sleep simulation for memory processing.',
  category: 'drishti',
  binduColor: 'indigo',
  trajectory: 'vertical',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0.4, easing: 'linear' },
  cycleDuration: 800,
  defaultSessionDuration: 120_000,
  phases: [
    { type: 'movement', duration: 20_000, instruction: 'Быстрые движения вверх-вниз. Старайтесь не отставать.' },
    { type: 'fixation', duration: 10_000, instruction: 'Пауза. Позвольте глазам отдохнуть.' },
    { type: 'movement', duration: 20_000 },
    { type: 'fixation', duration: 10_000, instruction: 'Отдых. Дышите глубоко.' },
    { type: 'movement', duration: 20_000 },
    { type: 'fixation', duration: 10_000 },
    { type: 'movement', duration: 20_000 },
    { type: 'eyes-closed', duration: 10_000, instruction: 'Закройте глаза. Обратите внимание на ощущения за веками.' },
  ],
  audioConfig: { mode: 'binaural', frequency: 200, waveform: 'sine', binauralDelta: 6 },
  requiresHeadphones: true,
  instruction: 'Это быстрый паттерн — точка движется вверх-вниз в ускоренном темпе. Старайтесь следить глазами, даже если не получается идеально. В паузах — расслабьте глаза. Этот режим имитирует быстрые движения глаз в фазе REM-сна.',
  effect: 'Интенсивная стимуляция, напоминающая фазу быстрого сна. Может вызвать ощущение \'обработки\' — как будто мозг сортирует информацию. После сессии возможна лёгкая усталость глаз и ощущение ясности.',
  origins: 'Anuvritta — быстрые вертикальные саккады из Натья Шастры. Напоминают движения глаз в REM-фазе сна, когда мозг консолидирует память. Стикголд (2002) предположил, что EMDR воспроизводит этот механизм наяву.',
  benefits: ['REM simulation', 'memory processing', 'emotional discharge', 'cognitive clarity'],
  defaultBackground: 'penrose',
  defaultBackgroundRotation: 'cw',
}

export const avalokita: PatternConfig = {
  id: 'avalokita',
  name: 'Avalokita',
  nameSanskrit: 'Avalokita',
  nameDevanagari: 'अवलोकित',
  description: 'Downward gaze. Grounding vertical movement for body awareness.',
  category: 'drishti',
  binduColor: 'teal',
  trajectory: 'vertical',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0.42, easing: 'sine', bias: 'down' },
  cycleDuration: 3500,
  defaultSessionDuration: 120_000,
  phases: [
    { type: 'movement', duration: 40_000, instruction: 'Следите за точкой. Мягкие движения вниз и обратно.' },
    { type: 'fixation', duration: 15_000, instruction: 'Точка внизу. Обратите внимание на ощущения в теле: ноги, живот, дыхание.' },
    { type: 'movement', duration: 40_000 },
    { type: 'fixation', duration: 15_000, instruction: 'Что вы чувствуете в теле прямо сейчас?' },
    { type: 'eyes-closed', duration: 10_000, instruction: 'Закройте глаза. Ощутите контакт тела с поверхностью.' },
  ],
  audioConfig: { mode: 'rhythmic', frequency: 196, waveform: 'sine', rhythmBPM: 45, subBass: 65 },
  requiresHeadphones: false,
  instruction: 'Точка движется в нижней части экрана. Следите глазами, направляя взгляд вниз. Обращайте внимание на телесные ощущения: тяжесть, тепло, контакт с поверхностью. Этот паттерн помогает \'заземлиться\'.',
  effect: 'Ощущение заземления, возвращение в тело. Снижает деперсонализацию и диссоциацию. Помогает перейти от \'головы\' к телесному осознаванию. Хорошо после интенсивной эмоциональной работы.',
  origins: 'Avalokita — нисходящий взгляд из Натья Шастры. Выражает смирение, созерцание, связь с землёй. В соматической психотерапии нисходящий взгляд помогает переключить внимание с мыслей на телесные ощущения.',
  benefits: ['grounding', 'body awareness', 'dissociation reduction', 'somatic processing'],
  defaultBackground: 'ripples',
  defaultBackgroundRotation: 'cw',
}

export const trataka: PatternConfig = {
  id: 'trataka',
  name: 'Trataka',
  nameSanskrit: 'Trataka',
  nameDevanagari: 'त्राटक',
  description: 'Candle flame gazing. Concentration training with afterimage observation.',
  category: 'drishti',
  binduColor: 'saffron',
  trajectory: 'fixation',
  visual: 'flame',
  trajectoryParams: { amplitude: 0, easing: 'linear' },
  cycleDuration: null,
  defaultSessionDuration: 300_000,
  phases: [
    { type: 'fixation', duration: 60_000, instruction: 'Смотрите на пламя, не моргая. Если слёзы — это нормально.' },
    { type: 'eyes-closed', duration: 30_000, instruction: 'Закройте глаза. Наблюдайте остаточный образ пламени за веками.' },
    { type: 'fixation', duration: 60_000, instruction: 'Откройте глаза. Снова сосредоточьтесь на пламени.' },
    { type: 'eyes-closed', duration: 30_000, instruction: 'Закройте глаза. Образ может быть другого цвета — это нормально.' },
    { type: 'fixation', duration: 60_000, instruction: 'Последний раунд. Мягко, без напряжения.' },
    { type: 'eyes-closed', duration: 60_000, instruction: 'Финальное наблюдение. Позвольте образу раствориться естественно.' },
  ],
  audioConfig: { mode: 'drone', frequency: 164.81, waveform: 'sine', droneIntervals: [1, 1.25, 1.5, 2], pitchLFO: 3, pinkNoise: 0.02 },
  requiresHeadphones: false,
  instruction: 'Классическая практика фиксации взгляда на пламени. Смотрите, не моргая, пока глаза не начнут слезиться — это нормально и даже полезно. Затем закройте глаза и наблюдайте за остаточным образом (послеобразом) — цветным пятном за закрытыми веками. Не пытайтесь его удержать, просто наблюдайте.',
  effect: 'Глубокая концентрация, очищение зрительного аппарата (слёзы увлажняют). Наблюдение послеобраза — естественная визуализация без усилий. Исследования показывают улучшение внимания, снижение тревоги, улучшение качества сна.',
  origins: 'Тратака описана в Хатха Йога Прадипике как одна из шести шаткарм (очистительных практик). Индийские танцоры используют её для тренировки неподвижного, выразительного взгляда. Пламя генерируется программно на Canvas.',
  benefits: ['concentration', 'eye health', 'anxiety reduction', 'sleep quality', 'natural visualization'],
  defaultBackground: 'metatrons-cube',
  defaultBackgroundRotation: 'cw',
}

export const emdrClassic: PatternConfig = {
  id: 'emdr_classic',
  name: 'EMDR Classic',
  nameSanskrit: '',
  nameDevanagari: '',
  description: 'Standard EMDR bilateral stimulation. Most researched form.',
  category: 'emdr',
  binduColor: 'saffron',
  trajectory: 'horizontal',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0.50, easing: 'sine' },
  cycleDuration: 1400,
  defaultSessionDuration: 300_000,
  phases: [
    { type: 'movement', duration: 25_000, instruction: 'Следите за точкой.' },
    { type: 'fixation', duration: 8_000, instruction: 'Глубокий вдох. Что замечаете?' },
    { type: 'movement', duration: 25_000 },
    { type: 'fixation', duration: 8_000, instruction: 'Что приходит сейчас?' },
    { type: 'movement', duration: 25_000 },
    { type: 'fixation', duration: 8_000 },
    { type: 'movement', duration: 25_000 },
    { type: 'fixation', duration: 8_000 },
    { type: 'movement', duration: 25_000 },
    { type: 'fixation', duration: 8_000, instruction: 'Что изменилось по сравнению с началом?' },
  ],
  audioConfig: { mode: 'bilateral', frequency: 396, waveform: 'sine' },
  requiresHeadphones: true,
  instruction: 'Стандартная EMDR-стимуляция. Точка движется из стороны в сторону. Следите глазами. В паузах — отмечайте мысли, ощущения, образы. Не пытайтесь контролировать процесс — просто наблюдайте, что приходит. Если становится слишком интенсивно — поставьте на паузу.',
  effect: 'Снижение эмоциональной нагрузки тревожных мыслей и воспоминаний. Стандартный EMDR-протокол — наиболее исследованная форма билатеральной стимуляции.',
  origins: 'EMDR (Eye Movement Desensitization and Reprocessing) разработан Франсин Шапиро в 1989 году. Признан ВОЗ как эффективный метод лечения ПТСР.',
  benefits: ['trauma processing', 'anxiety reduction', 'emotional regulation', 'PTSD symptom reduction'],
  defaultBackground: 'zen',
  defaultBackgroundRotation: 'none',
}

export const emdrDiagonal: PatternConfig = {
  id: 'emdr_diagonal',
  name: 'EMDR Diagonal',
  nameSanskrit: '',
  nameDevanagari: '',
  description: 'Diagonal bilateral stimulation. Engages more oculomotor muscles.',
  category: 'emdr',
  binduColor: 'saffron',
  trajectory: 'diagonal',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0.40, easing: 'sine' },
  cycleDuration: 1800,
  defaultSessionDuration: 180_000,
  phases: [
    { type: 'movement', duration: 30_000, instruction: 'Следите за точкой по диагонали.' },
    { type: 'fixation', duration: 10_000, instruction: 'Пауза.' },
    { type: 'movement', duration: 30_000 },
    { type: 'fixation', duration: 10_000 },
    { type: 'movement', duration: 30_000 },
    { type: 'fixation', duration: 10_000 },
  ],
  audioConfig: { mode: 'bilateral', frequency: 396, waveform: 'sine' },
  requiresHeadphones: true,
  instruction: 'Диагональный вариант билатеральной стимуляции. Точка движется из нижнего левого угла в верхний правый и обратно. Некоторым этот вариант подходит лучше, чем горизонтальный.',
  effect: 'Аналогично стандартному EMDR, но с дополнительной вертикальной компонентой. Задействует больше глазных мышц. Некоторые терапевты используют диагональные сеты, когда горизонтальные не дают достаточного эффекта.',
  origins: 'Вариация стандартного EMDR-протокола. Диагональные движения используются некоторыми EMDR-терапевтами как альтернатива горизонтальным.',
  benefits: ['trauma processing', 'alternative bilateral pattern', 'full oculomotor activation'],
  defaultBackground: 'zen',
  defaultBackgroundRotation: 'none',
}

export const sleepRem: PatternConfig = {
  id: 'sleep_rem',
  name: 'REM Sleep',
  nameSanskrit: '',
  nameDevanagari: '',
  description: 'Slow figure-8 with binaural theta beats. Pre-sleep relaxation.',
  category: 'sleep',
  binduColor: 'indigo',
  trajectory: 'figure8',
  visual: 'bindu',
  trajectoryParams: { amplitude: 0.35, easing: 'sine' },
  cycleDuration: 6000,
  defaultSessionDuration: 300_000,
  phases: [
    { type: 'movement', duration: 60_000, instruction: 'Следите за точкой. Позвольте глазам расслабиться.' },
    { type: 'fixation', duration: 15_000, instruction: 'Глаза полуоткрыты. Дышите медленно.' },
    { type: 'movement', duration: 60_000, instruction: 'Продолжайте. Если глаза начинают закрываться — это нормально.' },
    { type: 'fixation', duration: 15_000 },
    { type: 'movement', duration: 60_000 },
    { type: 'eyes-closed', duration: 90_000, instruction: 'Закройте глаза. Позвольте телу расслабиться. Если заснёте — это хорошо.' },
  ],
  audioConfig: { mode: 'binaural', frequency: 180, waveform: 'sine', binauralDelta: 4 },
  requiresHeadphones: true,
  instruction: 'Медленный, плавный паттерн, имитирующий движения глаз в фазе быстрого сна. Точка движется по восьмёрке. Не нужно следить идеально — позвольте глазам расслабиться. Режим предназначен для использования перед сном.',
  effect: 'Расслабление, подготовка ко сну. Бинауральные тета-биты (4 Hz) помогают мозгу перейти в состояние, предшествующее сну. Медленная восьмёрка убаюкивает без стимуляции.',
  origins: 'Вдохновлён исследованиями REM-фазы сна. Гипотеза Стикголда: движения глаз в REM-сне помогают мозгу переносить эмоционально заряженные воспоминания в долговременную память. Этот режим воссоздаёт похожий паттерн.',
  benefits: ['sleep preparation', 'relaxation', 'memory consolidation', 'stress reduction'],
  defaultBackground: 'aura',
  defaultBackgroundRotation: 'cw',
}

/** All patterns in display order (gentle → intense) */
export const allPatterns: PatternConfig[] = [
  nimilita, sama, sleepRem, avalokita, trataka, alokita,
  sachi, ullokita, pralokita, emdrClassic, emdrDiagonal, anuvritta,
]

/** Lookup by id */
export const patternsById = Object.fromEntries(
  allPatterns.map((p) => [p.id, p])
) as Record<string, PatternConfig>
